# Generated by Django 5.1.3 on 2024-12-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='공연명')),
                ('place', models.CharField(max_length=255, verbose_name='공연 장소')),
                ('start_date', models.DateField(verbose_name='공연 시작일')),
                ('end_date', models.DateField(verbose_name='공연 종료일')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='공연 시간(분)')),
            ],
            options={
                'verbose_name': '공연 정보',
                'verbose_name_plural': '공연 정보들',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='리뷰 작성자 닉네임')),
                ('date', models.DateField(verbose_name='리뷰 작성일')),
                ('view_count', models.IntegerField(default=0, verbose_name='리뷰 조회수')),
                ('like_count', models.IntegerField(default=0, verbose_name='리뷰 좋아요 수')),
                ('title', models.CharField(max_length=255, verbose_name='리뷰 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='리뷰 내용')),
                ('star_rating', models.FloatField(blank=True, null=True, verbose_name='리뷰 별점')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.concert', verbose_name='공연')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰들',
            },
        ),
    ]
