# Generated by Django 5.1.3 on 2024-12-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': '공연 정보', 'verbose_name_plural': '공연 정보'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '리뷰', 'verbose_name_plural': '리뷰'},
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('day_num', models.IntegerField(verbose_name='일')),
                ('day_str', models.CharField(max_length=10, verbose_name='요일')),
                ('round_name', models.CharField(max_length=10, verbose_name='회차 번호')),
                ('round_time', models.TimeField(verbose_name='회차 시간')),
                ('seat_class', models.CharField(max_length=10, verbose_name='좌석 등급')),
                ('count', models.IntegerField(verbose_name='잔여 좌석')),
                ('actors', models.TextField(blank=True, help_text='해당 회차에 캐스팅된 배우 목록을 저장합니다.', verbose_name='캐스팅 배우들')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='review.concert', verbose_name='공연')),
            ],
            options={
                'verbose_name': '잔여 좌석 정보',
                'verbose_name_plural': '잔여 좌석 정보',
            },
        ),
    ]
