# Generated by Django 5.1.3 on 2024-12-12 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_concert_options_alter_review_options_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='count',
            new_name='seat_count',
        ),
        migrations.AddField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='이 데이터가 생성된 시간을 저장합니다.', verbose_name='데이터 삽입 시간'),
        ),
    ]
