# Generated by Django 5.1.3 on 2025-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_seat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='공연 장르'),
        ),
    ]
