# Generated by Django 5.1.3 on 2025-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_concert_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emotion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='리뷰 감정'),
        ),
    ]
