# Generated by Django 5.1.3 on 2025-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_review_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='슬랙 채널 ID'),
        ),
    ]
