# Generated by Django 5.1.3 on 2025-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_concert_slack_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='crawling_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='크롤링 URL'),
        ),
    ]
