# Generated by Django 5.1.3 on 2025-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_concert_crawling_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_crawling_enabled',
            field=models.BooleanField(default=False, verbose_name='크롤링 활성화 여부'),
        ),
    ]
