# Generated by Django 5.1.3 on 2025-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_concert_is_crawling_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_slack_enabled',
            field=models.BooleanField(default=False, verbose_name='슬랙 알림 활성화 여부'),
        ),
    ]
