# Generated by Django 5.0.2 on 2025-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_concert_is_slack_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_sentiment_enabled',
            field=models.BooleanField(default=False, verbose_name='감정분석 활성화 여부'),
        ),
    ]
